name: Deploy the documentation to GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-up:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '26'

      - name: Install dependencies
        run: npm ci

      - name: Build the documentations
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./docs/.vitepress/dist
          name: github-pages

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-up
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment