name: Test building with NPM
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-dev:
    name: Build NPM in Development mode
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node_version: ['22', '24']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repositoty
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node_version }}

      - name: Change directory to the target
        run: cd ./stockpilemanneo

      - name: Build in development mode
        run: npm run dev

      - name: Upload the artifacts.
        uses: actions/upload-artifact@v7
        with:
          path: |
            dist/**

  build:
    name: Build NPM in Production mode
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node_version: ['22', '24']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node_version }}

      - name: Change the directory
        run: cd ./stockpilemanneo

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v7
        with:
          path: dist/**